-- Table: main_diseases
CREATE TABLE main_diseases (
    disease_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    disease_name VARCHAR2(50) NOT NULL UNIQUE,
    description VARCHAR2(255)
);

-- Insert sample diseases
INSERT INTO main_diseases (disease_name, description) VALUES ('Malaria', 'Mosquito-borne infectious disease');
INSERT INTO main_diseases (disease_name, description) VALUES ('HIV/AIDS', 'Human Immunodeficiency Virus / Acquired Immunodeficiency Syndrome');
INSERT INTO main_diseases (disease_name, description) VALUES ('Stunting', 'Chronic malnutrition condition in children');
INSERT INTO main_diseases (disease_name, description) VALUES ('Respiratory Infections', 'Infections affecting the lungs and airways');
INSERT INTO main_diseases (disease_name, description) VALUES ('Diarrheal Diseases', 'Diseases causing severe diarrhea');

COMMIT;

SELECT * FROM main_diseases;
