-- Table: doctor
CREATE TABLE doctor (
    doctor_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    gender VARCHAR2(10),
    phone_number VARCHAR2(15),
    specialization VARCHAR2(100)
);

-- Sample doctor data
INSERT INTO doctor (first_name, last_name, gender, phone_number, specialization)
VALUES ('Alice', 'Uwase', 'Female', '0788123451', 'Malaria Specialist');

INSERT INTO doctor (first_name, last_name, gender, phone_number, specialization)
VALUES ('Pierre', 'Nkurunziza', 'Male', '0788234567', 'HIV/AIDS Specialist');

INSERT INTO doctor (first_name, last_name, gender, phone_number, specialization)
VALUES ('Jean Bosco', 'Habimana', 'Male', '0788345678', 'Pediatrician');

INSERT INTO doctor (first_name, last_name, gender, phone_number, specialization)
VALUES ('Claire', 'Mukandayisenga', 'Female', '0788456789', 'Respiratory Specialist');

INSERT INTO doctor (first_name, last_name, gender, phone_number, specialization)
VALUES ('Eric', 'Niyonsenga', 'Male', '0788567890', 'Nutritionist');

SELECT *FROM doctor;