CREATE TABLE lab_technician (
    lab_test_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    patient_id NUMBER NOT NULL,
    test_type VARCHAR2(100) NOT NULL,
    test_result VARCHAR2(100),
    test_date DATE DEFAULT SYSDATE,
    lab_technician_name VARCHAR2(100),
    lab_department VARCHAR2(50),
    test_status VARCHAR2(20) DEFAULT 'Completed',
    remarks VARCHAR2(255),
    CONSTRAINT fk_lab_patient FOREIGN KEY (patient_id) REFERENCES reception(patient_id)
);

-- Insert sample lab tests
INSERT INTO lab_technician (patient_id, test_type, test_result, lab_technician_name, lab_department, test_status, remarks)
VALUES (1, 'Malaria Test', 'Positive', 'Jean Bosco', 'Parasitology', 'Completed', 'Patient requires follow-up in 2 weeks');

INSERT INTO lab_technician (patient_id, test_type, test_result, lab_technician_name, lab_department, test_status, remarks)
VALUES (2, 'HIV Test', 'Negative', 'Aline Uwase', 'Virology', 'Completed', 'Routine annual test');

INSERT INTO lab_technician (patient_id, test_type, test_result, lab_technician_name, lab_department, test_status, remarks)
VALUES (3, 'Blood Sugar Test', 'High', 'Emmanuel Niyonsaba', 'Biochemistry', 'Completed', 'Patient advised dietary changes');

INSERT INTO lab_technician (patient_id, test_type, test_result, lab_technician_name, lab_department, test_status, remarks)
VALUES (4, 'Malaria Test', 'Negative', 'Sandrine Mukamana', 'Parasitology', 'Completed', 'No treatment needed');

INSERT INTO lab_technician (patient_id, test_type, test_result, lab_technician_name, lab_department, test_status, remarks)
VALUES (5, 'HIV Test', 'Positive', 'Jean Bosco', 'Virology', 'Completed', 'Patient referred to ART clinic');


SELECT *FROM lab_technician;