-- Table: other_diseases
CREATE TABLE other_diseases (
    other_disease_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    disease_name VARCHAR2(100) NOT NULL UNIQUE,
    description VARCHAR2(255)
);

-- Sample inserts
INSERT INTO other_diseases (disease_name, description) 
VALUES ('Cholera', 'Bacterial infection causing severe diarrhea');

INSERT INTO other_diseases (disease_name, description) 
VALUES ('Typhoid', 'Bacterial infection causing fever and weakness');

INSERT INTO other_diseases (disease_name, description) 
VALUES ('Ebola', 'Viral hemorrhagic fever with high fatality rate');

SELECT * FROM other_diseases;
