-- Table: reception
CREATE TABLE reception (
    patient_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    gender VARCHAR2(10),
    date_of_birth DATE,
    phone_number VARCHAR2(20),
    email VARCHAR2(100),
    address VARCHAR2(255),
    disease_name VARCHAR2(100) NOT NULL, -- links to main_diseases or other_diseases
    visit_date DATE DEFAULT SYSDATE,
    doctor_id NUMBER, -- FK to doctor table (will create later)
    lab_technician_id NUMBER, -- FK to lab_technician table (will create later)
    treatment_id NUMBER, -- FK to treatment table (will create later)
    CONSTRAINT fk_reception_disease FOREIGN KEY (disease_name) 
        REFERENCES main_diseases(disease_name)
);

-- Sample patient data for reception table
INSERT INTO reception (first_name, last_name, gender, date_of_birth, phone_number, disease_name)
VALUES ('Jean', 'Uwimana', 'Male', TO_DATE('1990-05-12','YYYY-MM-DD'), '0788123456', 'Malaria');

INSERT INTO reception (first_name, last_name, gender, date_of_birth, phone_number, disease_name)
VALUES ('Aline', 'Mukamana', 'Female', TO_DATE('1985-03-22','YYYY-MM-DD'), '0788765432', 'HIV/AIDS');

INSERT INTO reception (first_name, last_name, gender, date_of_birth, phone_number, disease_name)
VALUES ('Emmanuel', 'Niyonzima', 'Male', TO_DATE('1992-08-15','YYYY-MM-DD'), '0788123987', 'Stunting');

INSERT INTO reception (first_name, last_name, gender, date_of_birth, phone_number, disease_name)
VALUES ('Claudine', 'Ishimwe', 'Female', TO_DATE('2000-12-05','YYYY-MM-DD'), '0788432190', 'Respiratory Infections');

INSERT INTO reception (first_name, last_name, gender, date_of_birth, phone_number, disease_name)
VALUES ('Eric', 'Habimana', 'Male', TO_DATE('1995-07-20','YYYY-MM-DD'), '0788675309', 'Diarrheal Diseases');
