
-- PUBLIC HOLIDAYS TABLE

CREATE TABLE public_holidays (
    holiday_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    holiday_date DATE NOT NULL UNIQUE,
    description  VARCHAR2(200)
);

-- Example upcoming holidays
INSERT INTO public_holidays (holiday_date, description)
VALUES (DATE '2025-12-25', 'Christmas Day');

INSERT INTO public_holidays (holiday_date, description)
VALUES (DATE '2026-01-01', 'New Year Day');

COMMIT;

-- AUDIT LOG TABLE

CREATE TABLE audit_log (
    audit_id       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username       VARCHAR2(100),
    user_terminal  VARCHAR2(100),
    action_type    VARCHAR2(20),
    target_table   VARCHAR2(100),
    target_pk      VARCHAR2(200),
    action_time    TIMESTAMP DEFAULT SYSTIMESTAMP,
    success_flag   CHAR(1),
    reason         VARCHAR2(4000),
    sql_text       CLOB
);


-- AUDIT PROCEDURE


CREATE OR REPLACE PROCEDURE log_audit(
    p_username    IN VARCHAR2,
    p_terminal    IN VARCHAR2,
    p_action      IN VARCHAR2,
    p_table       IN VARCHAR2,
    p_target_pk   IN VARCHAR2,
    p_success     IN CHAR,
    p_reason      IN VARCHAR2,
    p_sql_text    IN CLOB
) IS
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    INSERT INTO audit_log(
        username, user_terminal, action_type, target_table,
        target_pk, action_time, success_flag, reason, sql_text
    ) VALUES (
        p_username, p_terminal, p_action, p_table,
        p_target_pk, SYSTIMESTAMP, p_success, p_reason, p_sql_text
    );
    COMMIT;
END;
/



-- restricted days & days

CREATE OR REPLACE FUNCTION is_restricted_day(p_date IN DATE)
RETURN BOOLEAN IS
    v_cnt NUMBER;
    v_dow NUMBER;
BEGIN
    -- Is holiday?
    SELECT COUNT(*)
    INTO v_cnt
    FROM public_holidays
    WHERE TRUNC(holiday_date) = TRUNC(p_date);

    IF v_cnt > 0 THEN
        RETURN TRUE;
    END IF;

    -- Check weekday restriction (Mon–Fri)
    v_dow := TO_NUMBER(TO_CHAR(p_date,'D'));

    IF v_dow BETWEEN 2 AND 6 THEN
        RETURN TRUE;
    END IF;

    RETURN FALSE;  -- Weekend allowed
END;
/


-- SIMPLE TRIGGER

CREATE OR REPLACE TRIGGER trg_reception_restrict
BEFORE INSERT OR UPDATE OR DELETE ON reception
FOR EACH ROW
DECLARE
    v_user  VARCHAR2(100) := SYS_CONTEXT('USERENV','SESSION_USER');
    v_term  VARCHAR2(100) := SYS_CONTEXT('USERENV','TERMINAL');
    v_action VARCHAR2(10);
    v_pk VARCHAR2(200);
BEGIN
    -- Determine action
    IF INSERTING THEN
        v_action := 'INSERT';
        v_pk := 'NEW';  
    ELSIF UPDATING THEN
        v_action := 'UPDATE';
        v_pk := 'ID=' || :OLD.patient_id;
    ELSE
        v_action := 'DELETE';
        v_pk := 'ID=' || :OLD.patient_id;
    END IF;

    -- Restriction rule check
    IF is_restricted_day(SYSDATE) THEN
        log_audit(v_user, v_term, v_action, 'RECEPTION',
                  v_pk, 'N', 'Operation denied: restricted day.', NULL);
        RAISE_APPLICATION_ERROR(-20060, 'DML NOT ALLOWED: Weekday or Holiday.');
    END IF;

    -- Allowed
    log_audit(v_user, v_term, v_action, 'RECEPTION',
              v_pk, 'Y', NULL, NULL);
END;
/

-- coumpound trigger

CREATE OR REPLACE TRIGGER ctg_reception_audit
FOR INSERT OR UPDATE OR DELETE ON reception
COMPOUND TRIGGER

    TYPE t_info IS TABLE OF VARCHAR2(200);
    g_rows t_info := t_info();

BEFORE STATEMENT IS
BEGIN
    IF is_restricted_day(SYSDATE) THEN
        log_audit(
            SYS_CONTEXT('USERENV','SESSION_USER'),
            SYS_CONTEXT('USERENV','TERMINAL'),
            'BATCH_DML', 'RECEPTION', NULL, 'N',
            'Statement denied: restricted day.', NULL
        );
        RAISE_APPLICATION_ERROR(-20061, 'Batch DML NOT ALLOWED today.');
    END IF;
END BEFORE STATEMENT;

AFTER EACH ROW IS
BEGIN
    IF INSERTING THEN
        g_rows.EXTEND;
        g_rows(g_rows.COUNT) := 'INSERT ID=' || :NEW.patient_id;
    ELSIF UPDATING THEN
        g_rows.EXTEND;
        g_rows(g_rows.COUNT) := 'UPDATE ID=' || :OLD.patient_id;
    ELSE
        g_rows.EXTEND;
        g_rows(g_rows.COUNT) := 'DELETE ID=' || :OLD.patient_id;
    END IF;
END AFTER EACH ROW;

AFTER STATEMENT IS
BEGIN
    FOR i IN 1 .. g_rows.COUNT LOOP
        log_audit(
            SYS_CONTEXT('USERENV','SESSION_USER'),
            SYS_CONTEXT('USERENV','TERMINAL'),
            'BATCH_DML', 'RECEPTION',
            g_rows(i), 'Y', NULL, NULL
        );
    END LOOP;
END AFTER STATEMENT;

END ctg_reception_audit;
/

-- Testing 
-- Weekday Test → MUST BLOCK


SHOW ERRORS TRIGGER secure_reception;
SHOW ERRORS TRIGGER audit_reception;



UPDATE reception 
SET phone_number = '0788111111' 
WHERE patient_id = 1;

SELECT *
FROM audit_log
WHERE target_table = 'RECEPTION'
ORDER BY action_time DESC;


SELECT audit_id, username, action_type, target_table, target_pk, 
       success_flag, reason, action_time
FROM audit_log
ORDER BY action_time DESC;


INSERT INTO reception (first_name, last_name, gender, date_of_birth, phone_number, disease_name)
VALUES ('Test', 'User', 'Male', DATE '1990-01-01', '0788000000', 'Malaria');


